---
title: "2nd Draft of Challenges of Integrating Physical Exposure and Human Impacts Data in Tropical Cyclone Studies"
author: "Matthew Hughes and Brooke Anderson"
date: "February 16, 2021"
output: pdf_document
bibliography: bibliography.bib
---

# Introduction

Tropical cyclones---which encompasses hurricanes as well as tropical storms and tropical depressions--- regularly threaten coastal communities across the Eastern and Southern United States. From 2000 to 2019, tropical cyclones cost the United States at least 811 billion dollars in damages[@NOAA billion dollar disasters]. Tropical cyclones in that same time frame resulted in 6,010 human fatalities, averaging 301 deaths per year [@NOAA billion dollar disasters]. Tropical cyclones upset coastal communities and society by damaging property, disrupting local economies, and harming human health. This is why they are so critical to study. 

Tropical cyclones are environmental disaster events that are crucial for public health authorities and scientists to understand. Human mortality is an obvious consequence of these storms, and in 1992 Hurricane Andrew left 53 residents in Florida and surrounding states dead [@ahrens2005essentials]. However, many other chronic and long term health impacts have been observed in the aftermath of tropical cyclones. For example, researchers have observed that in utero exposure to tropical cyclones leads to adverse birth outcomes. [@kinney2008autism] observed higher rates of autism in children born to mothers who had higher rates of storm exposure than children born to mothers who were exposed to lower intensities. The scientific literature also reveals evidence of mental health outcomes associated with populations exposed to tropical cyclones. Survivors of tropical storms often report higher levels of depression, anxiety, and PTSD, due to reduced access to important medical and social services, property damages, poor sanitation, and displacement after storms [@lieberman2017self]. 

Beyond health impacts, both mental and physical, tropical storms create incredible strains on the economies of the Southeastern United States. The average cost of a tropical cyclone event in the US is 21.2 billion per event. [@NOAA billion dollar disasters]. Large population displacements often result from tropical cyclone events as well, such as the migration of Puerto Ricans to Florida after Hurricane Maria. [@scaramutti2019mental]

Clearly, tropical cyclones dramatically impact the social, economic, and physical wellbeing of  coastal communities. These extreme weather events represent an environmental health threat that is not going to disappear, and given that coastal regions of the Southeastern US are experiencing population growth, it is likely that higher numbers of people will be put at risk in the future. Avoiding these risks is not possible, but building resilience in communities after they experience tropical cyclone events is key to mitigating damages and preparing for future disasters. Creating lasting and resilient communities in areas prone to tropical cyclones  requires that researchers understand which populations and locations are at the greatest risk for negative exposures to tropical storms. High quality data allows researchers to assess where in space and time tropical storms occur, and also where in space and time individuals and populations are experiencing impacts from these storms. 

The key challenge for multidisciplinary teams to assess the human effects of tropical cyclones is integrating data from across disciplines. For example: extensive physical exposure data is often available for tropical cyclones as they near and cross communities in the United States. This data can come both from established monitoring networks, like [NOAA network name?], but may also result from data collection efforts during or after the storm by atmospheric scientists and engineers seeking to characterize a storm. Researchers studying the human impacts of these storms, including epidemiologists, economists, and social scientists are interested in this data as well, but the differences in temporal and spatial resolution makes the data harder to use. Resolving physical exposure and human impact datasets is challenging because the human impact data and physical exposure data often do not have congruent resolutions. 

Here we explore cases and implications of integrating data at different temporal and spatial scales, focusing as an example on human impact studies of tropical cyclones in the US. We begin by investigating the meteorological methods used for measuring physical exposures, and contrasting these with the ways in which human impacts data is used . We then describe the main spatial and temporal scales used, and finally assess some of the consequences that result from integrating physical exposure data with human impacts data. 

# Measuring Physical Exposures

Atmospheric and weather data are designed to give a picture of meteorological activity over vast geographic spreads as large as entire continents or oceanic basins. To acheive this, data is often recorded by sensors and instruments at fixed weather monitoring stations, in vast monitoring systems that are designed to automatically record a data point at a fixed interval of time. These monitoring systems are often the result of long-standing weather projects such as the National Hurricane Center Data Archive from NOAA (National Oceanic and Atmospheric Administration), and the NWS (National Weather Service). This data is often narrow in temporal and spatial resolution, and large in geographic scope. 

## Wind Speed and Direction

Wind speed is an extremely important element of tropical cyclones. To even be classified as a tropical cyclone, a storm must have wind speeds in excess of 74 miles per hour (64 knots). 

Meteorologists and atmospheric scientists use ground based wind instruments in set locations to measure wind speed and direction. One such instrument is called a wind vane. These can take on a variety of appearances such as wind socks at the airport, but they are essentially arrows that always point in the direction the wind is blowing. Anemometers measure wind speed by recording the rate of rotation of moving cups on a free moving shaft. An aerovane can measure both wind speed and wind direction and can be attached to a recorder to give continuous measurements. In order to be accurate and effective, these ground based wind instruments must be placed above the roofs of buildings so that they can be exposed to free flowing air. Since this is not always the case, wind observations can consequently be erratic in nature. 

Above ground, geostationary satellites, which are positioned above a particular location can measure wind speed and wind direction by observing the direction that clouds move in a given amount of time. Doppler radar can also be used to measure wind speed and direction. 

## Precipitation 

It is important to measure precipitation from tropical cyclones because not only does this give an indication of the cyclone's magnitude, but it also corresponds to damaging effects such as flooding. 

Rain gauges are the most well known instrument for measuring precipitation, but there are several different types of gauges. A standard rain gauge is simply a funnel shaped rain collector that is attached to a tube with measurements on the side. Measurements of rain less than 0.01 of an inch in a rain gauge are referred to as trace amounts. Tipping bucket rain gauges send electrical signals to a remote sensor every time a system of two buckets moves due to a known amount of water filling one of the buckets. Because a small amount of rain is lost whenever the buckets tip, this way of measuring rain is always an undercount. However, this is the type of rain gauge used by the automated weather stations.

Finally, similarly to wind speeds, radar and doppler radar can also be used to gauge precipitation. These technologies allow scientists to actually see the inside of a cloud and understand the amount of precipitation in that cloud. 

Excessive precipitation, sometimes in concert with storm surges, often leads to flooding; this is a more severe physical exposure that researchers are interested in. Stream gauges are often used to measure flooding, and tide stations, high water marks, and temporary barometric pressure sensors are used to measure the magnitude of storm surges. 

# Measuring Human Impacts

Where physical exposure data is often expansive and specific, owing to well established networks of weather monitoring stations, data on human impacts are spatially and temporally located within geopolitical, cultural, and administrative boundaries. This type of data is available often in the form of census records, hospitalization records and vitals statistics from hospitals and public health departments, disaster insurance claims, schools, and other systems that record human activities. Unlike the physical exposure data, these sources are often aggregated by geographic region and time, often out of convenience, or a need to preserve the anonymity and privacy of the people whose data is being used.  Researchers also will use such secondary datasets and sources to compare with primary data sources. For example in [@lieberman2017self], self reported flooding exposure data was compared to FEMA flooding exposure data. This goes to show that different disciplines have different aims and needs, and this creates spatial and temporal misalignment when multidisciplinary research is conducted. 




# References