---
title: "Examples of Exposure Misclassification"
author: "Matthew Hughes"
date: "April 21, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# [kinney2008autism]

This study tested a hypothesis that the risk of autistic disorder increases in a dose-response manner relative to the intensity of prenatal storm exposure, and that sensitive periods of gestation exist where these exposures are more likely to increase the risk of autistic disorder. The study was conducted in Louisiana parishes that had been hit by the storm centers from 1980 to 1995. 

- Individual gestation lengths were not available in this study, so a 40-week gestation was assumed. The 40-week gestation was divided into five eight week periods because the researchers wanted to understand if there were sensitive periods of gestation during which exposure to tropical storms could increase the risk of the child in utero having autism. There is a strong potential for misclassification of exposure here, because there is a potential for many pregnancies to be incorrectly divided five ways if they have longer or shorter gestations than 40 weeks. This could lead to incorrect risk assessments based on gestational period. Perhaps the eight weeks is a large enough bin to mitigate these effects. 

- Because the spatial scale of this study was at the level of individual parishes (the equivalent of counties in Louisiana), it is possible that exposure misclassification existed, relating to how intensely mothers were exposed during pregnancy. Three levels of severity of storm exposure for an individual Parish were defined as High (Storm Intensity and Storm Vulnerability both present), Intermediate (Either Storm Intensity or Storm Vulnerability present), or Low (Neither present). Storm intensity was assessed based on whether or not the center of the storm had passed through that parish. Storm vulnerability was a factor that described how vulnerable to a storm's effects residents would be if a storm center hit their parish. It is possible that some of the pregnant women living in these parishes designated as experiencing a high severity of storm intensity actually weren't as heaviliy exposed because they were not physically in that parish during the storm, or they lived in a part of it that experienced less severity than the average for that parish. Alternatively, some pregnant women in parishes designated as having a low vulnerability to storm intensity may have experienced much heavier exposure than recorded because they were in a part of that parish that was uniquely more vulnerable or experienced greater storm intensity than the parish as a whole. I believe this would be non-differential misclassification and would bias the results towards the null. 

# [grabich2016measuring]

- "Both disaster declarations and storm trajectory data may induce misclassification of exposure. Disaster
declarations are not intended for research, but rather for the provision of disaster assistance; moreover, hurricane force and damage is generally not symmetrical around the storm track, with maximum weather effects of hurricanes generally in the right-front quadrant, often northeast of the hurricane." [grabich2016measuring]

- Regarding misclassification of storm trajectory data, it is possible that many people classified as exposed would actually either be unexposed or simply less exposed than those who were located in the right front quadrant, or northeast of the hurricane. If there is an association between hurricane exposure during pregnancy and certain birth outcomes, then many pregnant women classified as exposed based on the storm trajectory would actually not being experiencing the maximum weather effects and this could potentially bias the results towards the null. 

- Regarding misclassification of disaster declarations, some of this could potentially be induced because as mentioned above disaster declarations are not intended for research but for providing disaster assistance. Potentially more people than are likely to be exposed are impacted by a disaster declaration if the goal is to be conservative and protect as many people. Similarly to above, this could lead to a misclassification of exposure that biases results towards the null.

- I think that both of these examples (disaster declarations and storm trajectory data) would lead to non-differential misclassifications.

# [grabich2016hurricane]

- "Hurricane exposure was classified by the hurricane’s maximum wind speed in a specific Florida county extracted from National Oceanic and Atmospheric Administration, Hurricane Research Division public databases (Grabich et al. 2015; NOAA, http://www.nhc.noaa.gov/dcmi.shtml). The Saffir Simpson Hurricane Scale categorizes hurricanes into five distinct categories of wind severity: Category 1 (74–95 miles per hour [mph]), 2 (96–110 mph), 3 (111–129 mph), 4 (130–156 mph), and 5 (157 and higher mph) while tropical storm wind speeds are classified as 39–73 mph (Zandbergen 2009). We categorized maximum wind speed using two binary categorizations based on the Saffir–Simpson wind scale: C39 mph to indicate tropical storm wind speed and C74 mph to indicate hurricane wind speed." [grabich2016hurricane]
- 


- "The 2004 hurricane season in Florida was atypical, as four hurricanes made landfall. Our analysis was primarily focused on the first hurricane of 2004, Hurricane Charley. Focusing on the first hurricane avoided bias that could affect analyses of later storms. For instance, for a later storm, women in counties unaffected by that storm could have been affected by an earlier storm that hit their county
only a few weeks earlier. Classifying women in these counties as unaffected could inaccurately attenuate associations between storm exposure and preterm outcomes. We additionally performed analysis adjusting for subsequent hurricane occurrences. Finally, we conducted analyses to investigate associations with exposure to multiple storms by that report hazard ratios for Hurricane Charley only exposure versus no hurricane exposure and hazard ratios comparing exposure to Hurricane Charley plus subsequent hurricanes to no exposure to any hurricanes." [grabich2016hurricane]

- 
